# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
import_types = ["crate::sqlite_mapping::*"]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
# sqlite_integer_primary_key_is_bigint = true

[migrations_directory]
dir = "/app/twinkle_server/migrations"
