[workspace]
resolver = "2"

members = [
	"twinkle_client",
	"twinkle_server",
	"indi",
	"phd2",
	"twinkle",
	"fits_inspect", "gtk_client", "leptos_client",
]

[workspace.dependencies]
twinkle_client = {path = "twinkle_client"}

[profile.dev.package.fits_inspect]
opt-level=3
