
[workspace]
members = [
    "egui-frontend",
    "fits_inspect",
    "indi",
    "phd2", "twinkle_api",
    "twinkle_client",
    "twinkle_server",
]
resolver = "2"

[profile.release]
opt-level = 2

[profile.dev]
opt-level = 2

[profile.dev.package.egui-frontend]
opt-level=0