[workspace]
resolver = "2"

members = [
	"twinkle_client",
	"indi",
	"phd2",
	"twinkle",
	"fits_inspect",
]

[workspace.dependencies]
twinkle_client = "0.1.0"

[profile.dev.package.fits_inspect]
opt-level=3
