volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  twinkle:
    image: twinkle
    tty: true
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - indi

  indi:
    image: indi
    command: indiserver -vvv indi_simulator_ccd indi_simulator_focus indi_simulator_guide indi_simulator_rotator indi_simulator_telescope indi_simulator_wheel
    ports:
      - "7624:7624"
